# syntax=docker/dockerfile:1

# stage 1: dependencies
FROM node:22-alpine AS deps

# openssl is required for the Prisma engine to work correctly in Alpine
RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# stage 2: build
FROM node:22-alpine AS build

RUN apk add --no-cache openssl

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# generate custom Prisma client in src/generated/prisma
RUN npx prisma generate

# build NestJS project (generates ./dist)
RUN npm run build

# copy generated Prisma client to dist,
# since tsc does not recompile the .js/.d.ts files already generated by Prisma
RUN cp -r src/generated dist/generated

# stage 3: production dependencies
FROM node:22-alpine AS prod-deps

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Prisma needs to generate the client here too, since prod-deps
# installs from scratch and the client is not a published npm package
COPY prisma ./prisma
RUN npx prisma generate

# stage 4: production image
FROM node:22-alpine AS runner

RUN apk add --no-cache openssl

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nestjs -u 1001

COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json

# necessary for the `prisma migrate deploy` command to run inside the container
# (schema, migrations and Prisma 7 config file)
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/prisma.config.ts ./prisma.config.ts

USER nestjs

EXPOSE 3000

CMD ["node", "dist/main"]