apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-IMAGE_TAG
  namespace: default
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: migrate
          image: ECR_REPOSITORY_PLACEHOLDER:IMAGE_TAG
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: nest-api-secret
      restartPolicy: Never