apiVersion: v1
kind: Secret
metadata:
  name: nest-api-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_TYPE: "mysql"
  DATABASE_HOST: "mariadb"
  DATABASE_PORT: "3306"
  DATABASE_USER: "MARIADB_USER_LOGIN_PLACEHOLDER"
  DATABASE_PASSWORD: "MARIADB_USER_PASSWORD_PLACEHOLDER"
  DATABASE_NAME: "MARIADB_DB_NAME_PLACEHOLDER"
  DATABASE_URL: "mysql://MARIADB_USER_LOGIN_PLACEHOLDER:MARIADB_USER_PASSWORD_PLACEHOLDER@mariadb:3306/MARIADB_DB_NAME_PLACEHOLDER"
  JWT_SECRET: "JWT_SECRET_PLACEHOLDER"
  JWT_ACCESS_EXPIRES_IN: "JWT_ACCESS_EXPIRES_IN_PLACEHOLDER"
  JWT_REFRESH_EXPIRES_IN: "JWT_REFRESH_EXPIRES_IN_PLACEHOLDER"
  ALLOWED_ORIGINS: "ALLOWED_ORIGINS_PLACEHOLDER"
  RATE_LIMIT_REQUESTS: "RATE_LIMIT_REQUESTS_PLACEHOLDER"
  RATE_LIMIT_SECONDS: "RATE_LIMIT_SECONDS_PLACEHOLDER"
  BCRYPT_SALT_ROUNDS: "BCRYPT_SALT_ROUNDS_PLACEHOLDER"
  DATABASE_CONNECTION_LIMIT: "DATABASE_CONNECTION_LIMIT_PLACEHOLDER"
  PORT: "PORT_PLACEHOLDER"